#!/bin/sh

# create all 10 shared directories, if they haven't already been created
if [ ! -d shared_directory_10 ]; then
	for i in $(seq 1 10); do
		mkdir shared_directory_"$i"
	done
fi

if [ -z "$3" ]; then
	dir="shared_directory_$(shuf -i 1-6 -n 1)"
	java -cp bin PeerMain "${1:-localhost}" "${2:-9090}" "$dir"
else
	java -cp bin PeerMain "${1:-localhost}" "${2:-9090}" "$3"
fi

exit $?
